### PR TITLE
Use 'application' & 'version' as required labels

### PR DESCRIPTION
**Pull request by mohabusama**
Use 'application' & 'version' as required labels

### CODE REVIEW

**Comment by mohabusama** [comment]
👍

**Comment by mikkeloscar** [comment]
What about the `release` label? Since it's required from the pipeline, we would also need it to list the logs of a specific release.

**Comment by hjacobs** [comment]
Yes, let's add `release`.

**Comment by mohabusama** [comment]
So we add it as a required label (if it doesn't exist then we won't follow the logs) or just add it to the job template as a log field?
@hjacobs @mikkeloscar

**Comment by mohabusama** [comment]
I went with optional field, since log agent doesn't require it.

**Comment by hjacobs** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Pull request merged**
